### ISSUE TITLE
Leaflet illustrate with medium editor

### ISSUE THREAD

**Issue by lstlim** [manleyjster/Leaflet.Illustrate#27]
Hi, is there any way I can integrate medium editor tool bar to leaflet illustrate textbox? I tried to link the medium editor object to the textbox but it does not work.

**Comment by justinmanley** [comment]
huh, I'm not sure if that'll work. It seems possible in principle. Looking at the [MediumEditor API](https://github.com/yabwe/medium-editor/blob/master/API.md#mediumeditorelements-options), it seems that they support textarea elements.

You could try listening for add events on the map, capture the event when it is an `L.Illustrate.Textbox`, and call `L.Illustrate.Textbox#getTextarea`, then pass the textarea into the MediumEditor API.

Beyond that I'd need to see more code or specific error messages to say whether this integration might work, or whether you'd be better off starting from scratch with vanilla Leaflet.
