### ISSUE TITLE
Attribution in example

### ISSUE THREAD

**Issue by jieter** [manleyjster/Leaflet.Illustrate#8]
The attribution for the tile layer in [the example](https://github.com/manleyjster/Leaflet.Illustrate/blob/master/examples/simple.html#L22-L24) mentions Stamen, while the layer is actually MapQuestOpen.
Should be something like:

```
'Tiles Courtesy of <a href="http://www.mapquest.com/">MapQuest</a> &mdash; Portions Courtesy NASA/JPL-Caltech and U.S. Depart. of Agriculture, Farm Service Agency'
```

**Comment by manleyjster** [comment]
Ah, sorry - you're completely right. Was originally using a Stamen layer,
then neglected to change the attribution when I changed the base layer.

Will fix this ASAP - thanks for noticing!

**Comment by jieter** [comment]
:+1:
